version: '3.9'

services:
  service_api_app:
    container_name: service_api_app
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uv run uvicorn --factory presentation.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '${SERVICE_API_PORT}:8000'
    volumes:
      - ../app/:/app
    env_file:
      - ../.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
