version: '3.9'

services:
  cache:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    ports:
      - "${CACHE_PORT}:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge