version: '3.9'

services:
  service_api_app:
    container_name: service_api_app
    build:
      dockerfile: Dockerfile
    command: "uv run uvicorn --factory presentation.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '${SERVICE_API_PORT}:8000'
    # volumes:
    #   - ./app/:/app
    env_file:
      - .env
    networks:
      - backend

  clickhouse-server:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      CLICKHOUSE_DB: ${DATABASE_CLICKHOUSE_NAME}
      CLICKHOUSE_USER: ${DATABASE_CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${DATABASE_CLICKHOUSE_PASSWORD}
    ports:
      - "${DATABASE_CLICKHOUSE_HTTP}:8123"
      - "${DATABASE_CLICKHOUSE_PORT}:9000"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - backend
    restart: always

volumes:
  local_pgdata:
  pgadmin-data:
  clickhouse-data:


networks:
  backend:
    driver: bridge
