version: '3.9'

services:
  service_api_app:
    container_name: service_api_app
    build:
      dockerfile: Dockerfile
    command: "uv run uvicorn --factory presentation.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '${SERVICE_API_PORT}:8000'
    # volumes:
    #   - ./app/:/app
    env_file:
      - .env
    networks:
      - backend

  db_postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend

  clickhouse-server:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      CLICKHOUSE_DB: ${DATABASE_CLICKHOUSE_NAME}
      CLICKHOUSE_USER: ${DATABASE_CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${DATABASE_CLICKHOUSE_PASSWORD}
    ports:
      - "${DATABASE_CLICKHOUSE_HTTP}:8123"
      - "${DATABASE_CLICKHOUSE_PORT}:9000"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - backend
    restart: always

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - "5521:5521"
    environment:
      VITE_CLICKHOUSE_URL: "http://clickhouse-server:${DATABASE_CLICKHOUSE_HTTP}"
      VITE_CLICKHOUSE_USER: ${DATABASE_CLICKHOUSE_USER}
      VITE_CLICKHOUSE_PASS: ${DATABASE_CLICKHOUSE_PASSWORD}
    networks:
      - backend

volumes:
  local_pgdata:
  pgadmin-data:
  clickhouse-data:

networks:
  backend:
    driver: bridge
